### ISSUE TITLE
S3 object store on aws should not require credentials

### ISSUE THREAD

**Issue by sstarcher** [deis/registry#44]
accesskey and secretkey should not be required as aws-sdk when running on an AWS instance will pull the credentials from the metadata service

**Comment by kmala** [comment]
fixed by #52

**Comment by ApsOps** [comment]
@kmala Looks like this is broken again by https://github.com/deis/registry/commit/3af11290c99b1b113934e5efa251bc8538947c2c cc: @bacongobbler 

If we don't set any aws access key or secret, it should fall back to using instance iam role (ec2 metadata api)
