### ISSUE TITLE
Look for minio and outside storage env vars

### ISSUE THREAD

**Issue by arschles** [deis/registry#7]
follow the lookup rules that [builder](https://github.com/deis/builder) and [workflow](https://github.com/deis/workflow) use:
- if `DEIS_MINIO_SERVICE_HOST` and `DEIS_MINIO_SERVICE_PORT` exist, use those for the S3 location
- if `DEIS_OUTSIDE_STORAGE_HOST` and `DEIS_OUTSIDE_STORAGE_PORT`, exist, use those for the S3 location

**Comment by kmala** [comment]
#24 handles using storage based on appropriate environment variables.Currently it doesn't handle minio as there are few issue with it.Created a issue to fix it #25.
