### ISSUE TITLE
Version 2.3.x makes deployment/deis-registry fail

### ISSUE THREAD

**Issue by ineu** [deis/registry#77]
I had Deis 2.8 installed. Recently I've installed 2.9 instead via `helm upgrade` and deis-registry stuck in CrashLoopBackOff. The error from the container is as follows: https://gist.github.com/ineu/37abac07168386bbc80496332da45245

DNS works fine in the container. I suspect that there's some issue in extracting host part from the swift.authurl in the 2.3.x, which makes it try to resolve not the host part but a full url.

I managed to fix it by using 2.2 image:
```
kd set image deploy/deis-registry deis-registry=quay.io/deis/registry:v2.2.4
```

**Comment by vdice** [comment]
@ineu could you add some further information, such as:

 - k8s version
 - Was 2.8 installed via Helm Classic (helmc) or Kubernetes Helm?

**Comment by ineu** [comment]
k8s 1.2
2.8 was installed via helmc, then it was removed with all secrets and 2.9 installed via k8s helm

**Comment by bacongobbler** [comment]
As suggested in other tickets prior to this can you try upgrading to k8s v1.3.10 (or v1.4.6) and see if that resolves the issue?

See https://github.com/deis/workflow/pull/625, we stopped testing v1.2 for some time now

**Comment by ineu** [comment]
Fresh installation of Deis 2.9 on the Kube 1.4 cluster doesn't suffer from this issue. I think this ticket can be closed.
